//! Level-of-detail system — quality selection based on camera distance.
//!
//! Maps tessellation quality levels to screen-space error thresholds and
//! selects the appropriate LOD for each mesh based on its distance from
//! the camera.

/// Quality levels for mesh tessellation.
///
/// Corresponds to the tessellation deflection values in the geometry crate.
/// Each level trades geometric fidelity for lower triangle count.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum LodLevel {
    /// Bare minimum — fast loading, worst quality.  Large deflection.
    Preview = 0,
    /// Balanced quality, suitable for general viewing.
    Standard = 1,
    /// Full quality, suitable for screenshot, measurement, or close inspection.
    High = 2,
}

impl LodLevel {
    /// Linear deflection as a fraction of the bounding-box diagonal.
    ///
    /// These values match the tessellation quality table in the architecture:
    /// - Preview:  bbox_diag * 0.002
    /// - Standard: bbox_diag * 0.0005
    /// - High:     bbox_diag * 0.0001
    pub fn deflection_fraction(self) -> f64 {
        match self {
            LodLevel::Preview => 0.002,
            LodLevel::Standard => 0.0005,
            LodLevel::High => 0.0001,
        }
    }
}

/// Selects LOD levels based on camera distance and geometric size.
#[derive(Debug, Clone)]
pub struct LodSelector {
    /// Distance thresholds (world units) for each LOD transition.
    ///
    /// - closer than `near` → High
    /// - between `near` and `far` → Standard
    /// - beyond `far` → Preview
    pub near: f32,
    pub far: f32,
}

impl LodSelector {
    /// Create with sensible defaults for a typical industrial model viewer.
    ///
    /// Default thresholds:
    /// - near = 10.0 (within 10 world units → High)
    /// - far  = 100.0 (beyond 100 → Preview)
    /// - between → Standard
    pub fn new() -> Self {
        Self {
            near: 10.0,
            far: 100.0,
        }
    }

    /// Scale thresholds by a factor (e.g. based on model size).
    pub fn scaled(self, factor: f32) -> Self {
        Self {
            near: self.near * factor,
            far: self.far * factor,
        }
    }

    /// Select the LOD level for an object at the given distance from the camera.
    ///
    /// `distance` is in world units (typically the distance from the camera eye
    /// to the object's bounding-sphere center).
    pub fn select(&self, distance: f32) -> LodLevel {
        if distance <= self.near {
            LodLevel::High
        } else if distance <= self.far {
            LodLevel::Standard
        } else {
            LodLevel::Preview
        }
    }

    /// Select LOD based on object bounds and camera position.
    ///
    /// Uses the distance from the camera to the bounding-sphere center.
    pub fn select_for_bounds(&self, center: glam::Vec3, camera_eye: glam::Vec3) -> LodLevel {
        let distance = (center - camera_eye).length();
        self.select(distance)
    }

    /// Determine whether two LOD levels can share the same mesh data.
    ///
    /// In practice, only the finest level is generated by tessellation;
    /// coarser levels could be derived via mesh simplification in a future
    /// iteration.  For now, this returns `true` so all LOD levels share
    /// the single tessellated mesh.
    pub fn can_share_mesh(_from: LodLevel, _to: LodLevel) -> bool {
        true
    }
}

impl Default for LodSelector {
    fn default() -> Self {
        Self::new()
    }
}

/// Result of selecting an LOD level for a batch of instances.
#[derive(Debug, Clone)]
pub struct LodSelection {
    pub level: LodLevel,
    /// Whether this batch should be drawn at this LOD level.
    pub visible: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deflection_fractions_match_tessellation_table() {
        assert!((LodLevel::Preview.deflection_fraction() - 0.002).abs() < 1e-9);
        assert!((LodLevel::Standard.deflection_fraction() - 0.0005).abs() < 1e-9);
        assert!((LodLevel::High.deflection_fraction() - 0.0001).abs() < 1e-9);
    }

    #[test]
    fn select_by_distance() {
        let selector = LodSelector::new();
        assert_eq!(selector.select(5.0), LodLevel::High);
        assert_eq!(selector.select(50.0), LodLevel::Standard);
        assert_eq!(selector.select(200.0), LodLevel::Preview);
    }

    #[test]
    fn select_at_threshold() {
        let selector = LodSelector::new();
        assert_eq!(selector.select(10.0), LodLevel::High);
        assert_eq!(selector.select(100.0), LodLevel::Standard);
    }

    #[test]
    fn scaled_thresholds() {
        let selector = LodSelector::new().scaled(2.0);
        assert_eq!(selector.select(15.0), LodLevel::High);
        assert_eq!(selector.select(150.0), LodLevel::Standard);
        assert_eq!(selector.select(250.0), LodLevel::Preview);
    }

    #[test]
    fn select_for_bounds() {
        let selector = LodSelector::new();
        let eye = glam::Vec3::new(0.0, 0.0, 5.0);
        let center = glam::Vec3::new(0.0, 0.0, 0.0);
        assert_eq!(selector.select_for_bounds(center, eye), LodLevel::High);
    }

    #[test]
    fn lod_level_ordering() {
        assert!(LodLevel::Preview < LodLevel::Standard);
        assert!(LodLevel::Standard < LodLevel::High);
    }

    #[test]
    fn can_share_mesh_currently_true() {
        assert!(LodSelector::can_share_mesh(
            LodLevel::Preview,
            LodLevel::High
        ));
    }
}
