//! STEP file format detection.
//!
//! Detection reads the first bytes of a file looking for the STEP header
//! marker.  It does **not** rely on file extensions.

use mmforge_core::parser::DetectionConfidence;
use std::path::Path;

/// The STEP magic string that must appear at the start of every
/// ISO 10303-21 file.
const STEP_MAGIC: &[u8] = b"ISO-10303-21;";

/// Known STEP file extensions (used as a weak hint only).
const STEP_EXTENSIONS: &[&str] = &["stp", "step", "p21"];

/// Detect whether a file is a STEP file based on header bytes.
///
/// Returns `Some(DetectionResult)` if the header matches, `None` otherwise.
pub fn detect_step(header: &[u8], path: &Path) -> Option<mmforge_core::parser::DetectionResult> {
    // Strong match: header starts with the STEP magic.
    if header.starts_with(STEP_MAGIC) {
        return Some(mmforge_core::parser::DetectionResult {
            format_tag: "STEP",
            confidence: DetectionConfidence::High,
        });
    }

    // Weak match: extension hint + header contains "ISO-10303" somewhere.
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_ascii_lowercase());
    if ext.as_deref().is_some_and(|e| STEP_EXTENSIONS.contains(&e)) {
        let header_str = String::from_utf8_lossy(header);
        if header_str.contains("ISO-10303") {
            return Some(mmforge_core::parser::DetectionResult {
                format_tag: "STEP",
                confidence: DetectionConfidence::Medium,
            });
        }
        // Extension matches but no magic — low confidence.
        return Some(mmforge_core::parser::DetectionResult {
            format_tag: "STEP",
            confidence: DetectionConfidence::Low,
        });
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn detect_strong_magic() {
        let header = b"ISO-10303-21;\nHEADER;\nENDSEC;\n";
        let path = PathBuf::from("model.step");
        let result = detect_step(header, &path).unwrap();
        assert_eq!(result.format_tag, "STEP");
        assert_eq!(result.confidence, DetectionConfidence::High);
    }

    #[test]
    fn detect_strong_magic_ignores_extension() {
        let header = b"ISO-10303-21;\nHEADER;\n";
        let path = PathBuf::from("model.xyz");
        let result = detect_step(header, &path).unwrap();
        assert_eq!(result.confidence, DetectionConfidence::High);
    }

    #[test]
    fn detect_medium_with_extension_and_partial_magic() {
        let header = b"# ISO-10303 file generated by CAD\n";
        let path = PathBuf::from("model.stp");
        let result = detect_step(header, &path).unwrap();
        assert_eq!(result.confidence, DetectionConfidence::Medium);
    }

    #[test]
    fn detect_low_extension_only() {
        let header = b"random bytes with no magic";
        let path = PathBuf::from("model.step");
        let result = detect_step(header, &path).unwrap();
        assert_eq!(result.confidence, DetectionConfidence::Low);
    }

    #[test]
    fn no_detect_wrong_extension_and_no_magic() {
        let header = b"random bytes";
        let path = PathBuf::from("model.stl");
        assert!(detect_step(header, &path).is_none());
    }

    #[test]
    fn no_detect_empty_header() {
        let header = b"";
        let path = PathBuf::from("model.step");
        // Empty header, extension matches → Low confidence
        let result = detect_step(header, &path).unwrap();
        assert_eq!(result.confidence, DetectionConfidence::Low);
    }
}
