#!/bin/bash
# MMForge macOS Performance Baseline
# Run: bash docs/scripts/perf-baseline.sh
#
# Compatible with macOS /bin/bash 3.2 (no associative arrays).
# Requires: cargo, mmforge-cli built

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CLI="cargo run -p mmforge-cli --"

echo "# MMForge Performance Baseline"
echo "# Date: $(date '+%Y-%m-%d %H:%M')"
echo "# Platform: $(uname -m)"
echo "# Bash: $(/bin/bash --version 2>&1 | head -1)"
echo ""

# Fixture list: paired format-name file-path
# Format: FMT name on even indices, path on odd indices.
FIXTURES=(
  "STEP"  "$ROOT/crates/mmforge-geometry/testdata/PQ-04909-A.STEP"
  "IGES"  "$ROOT/crates/mmforge-geometry/testdata/box.igs"
  "STL"   "$ROOT/testdata/stl/box.stl"
  "glTF"  "$ROOT/testdata/gltf/box.gltf"
  "DXF"   "$ROOT/crates/mmforge-format-dxf/testdata/test.dxf"
)

run_one() {
  local FMT="$1"
  local FILE="$2"

  if [ ! -f "$FILE" ]; then
    echo "### $FMT: SKIPPED — fixture not found: $FILE"
    echo ""
    return
  fi

  local FILE_SIZE
  FILE_SIZE=$(du -h "$FILE" | cut -f1 2>/dev/null || echo "?")
  echo "### $FMT ($FILE_SIZE) — $FILE"
  echo '```'

  # Benchmark
  set +e
  local BENCH_OUT
  BENCH_OUT=$(cd "$ROOT" && $CLI benchmark "$FILE" --format text --iterations 3 2>&1)
  local BENCH_RC=$?
  set -e

  if [ $BENCH_RC -ne 0 ]; then
    echo "benchmark: FAILED (may need OCCT feature or GPU)"
    echo "$BENCH_OUT" | head -5
  else
    echo "$BENCH_OUT"
  fi

  echo ""

  # Info
  set +e
  cd "$ROOT" && $CLI info "$FILE" --format text 2>&1
  set -e

  echo '```'
  echo ""
}

echo "## Parse + Info Benchmarks"
echo ""

LEN=${#FIXTURES[@]}
for ((i=0; i<LEN; i+=2)); do
  FMT="${FIXTURES[$i]}"
  FILE="${FIXTURES[$((i+1))]}"
  run_one "$FMT" "$FILE"
done

echo "---"
echo "Generated by docs/scripts/perf-baseline.sh"
